version: '3.2'

services:
  development:
    image: node:12
    stdin_open: true
    volumes:
      - .:/home/node/app:cached
    working_dir: /home/node/app
    ports:
      - 9009:9009
    entrypoint:
      - yarn
      - storybook
    environment:
      HOST: '0.0.0.0'
  example:
    image: node:12
    stdin_open: true
    volumes:
      - ./dist:/home/node/app/dist
      - ./node_modules:/home/node/app/node_modules
      - ./example:/home/node/app/example:cached
    working_dir: /home/node/app/example
    ports:
      - 5000:3000
    entrypoint:
      - yarn
      - start
    environment:
      HOST: '0.0.0.0'
      SASS_PATH: 'node_modules:src'
